name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: presentation/revealjs-system/package-lock.json
        
    - name: Install dependencies
      working-directory: presentation/revealjs-system
      run: npm ci
      
    - name: Build presentations
      working-directory: presentation/revealjs-system
      run: |
        npm run build
        echo "Build completed successfully"
        ls -la presentations/
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'presentation/revealjs-system'

  deploy:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

  pdf-export:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: presentation/revealjs-system/package-lock.json
        
    - name: Install dependencies
      working-directory: presentation/revealjs-system
      run: npm ci
      
    - name: Build and Export PDFs
      working-directory: presentation/revealjs-system
      run: |
        npm run build
        npm run pdf
        
    - name: Upload PDF artifacts
      uses: actions/upload-artifact@v4
      with:
        name: presentation-pdfs
        path: presentation/revealjs-system/pdf-exports/
        retention-days: 90

  notify:
    if: always()
    runs-on: ubuntu-latest
    needs: [build, deploy, pdf-export]
    
    steps:
    - name: Notify deployment status
      run: |
        if [ "${{ needs.deploy.result }}" == "success" ]; then
          echo "✅ Deployment successful"
          echo "🌐 Site URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
        else
          echo "❌ Deployment failed"
        fi
        
        if [ "${{ needs.pdf-export.result }}" == "success" ]; then
          echo "📄 PDF export successful"
        else
          echo "❌ PDF export failed"
        fi