version: '3.8'

services:
  # Build Service - kompiliert den Code
  build:
    image: maven:3.8-openjdk-17
    container_name: architecture-training-build
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - maven-cache:/root/.m2
    command: mvn clean compile
    networks:
      - training-network

  # Test Service - führt alle Tests aus
  test:
    image: maven:3.8-openjdk-17
    container_name: architecture-training-test
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - maven-cache:/root/.m2
    command: mvn test
    networks:
      - training-network

  # Package Service - erstellt JAR-Dateien
  package:
    image: maven:3.8-openjdk-17
    container_name: architecture-training-package
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - maven-cache:/root/.m2
    command: mvn clean package -DskipTests
    networks:
      - training-network

  # Development Service - interaktive Entwicklungsumgebung
  dev:
    image: maven:3.8-openjdk-17
    container_name: architecture-training-dev
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - maven-cache:/root/.m2
    stdin_open: true
    tty: true
    command: /bin/bash
    networks:
      - training-network

  # CI Service - vollständiger Build mit allen Tests
  ci:
    image: maven:3.8-openjdk-17
    container_name: architecture-training-ci
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - maven-cache:/root/.m2
    command: mvn clean verify
    networks:
      - training-network

  # Quick Test - schneller Test einzelner Module
  test-day1:
    image: maven:3.8-openjdk-17
    container_name: architecture-training-test-day1
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - maven-cache:/root/.m2
    command: mvn test -pl day1-examples
    networks:
      - training-network

  test-day2:
    image: maven:3.8-openjdk-17
    container_name: architecture-training-test-day2
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - maven-cache:/root/.m2
    command: mvn test -pl day2-examples
    networks:
      - training-network

  test-day3:
    image: maven:3.8-openjdk-17
    container_name: architecture-training-test-day3
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - maven-cache:/root/.m2
    command: mvn test -pl day3-examples
    networks:
      - training-network

  test-day4:
    image: maven:3.8-openjdk-17
    container_name: architecture-training-test-day4
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - maven-cache:/root/.m2
    command: mvn test -pl day4-examples
    networks:
      - training-network

volumes:
  maven-cache:
    name: architecture-training-maven-cache

networks:
  training-network:
    name: architecture-training-network
    driver: bridge