version: '3.8'

services:
  # Main presentation service
  presentations:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production
    container_name: telekom-presentations
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - TZ=Europe/Berlin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.presentations.rule=Host(`presentations.local`)"
      - "traefik.http.routers.presentations.entrypoints=web"
      - "traefik.http.services.presentations.loadbalancer.server.port=80"
    networks:
      - presentation-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service for live editing
  dev:
    image: node:18-alpine
    container_name: telekom-presentations-dev
    working_dir: /app
    ports:
      - "3000:3000"
      - "8081:8080"
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "
        if [ ! -d node_modules ]; then
          echo '📦 Installing dependencies...'
          npm install
        fi
        echo '🚀 Starting development server...'
        npm run serve
      "
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    profiles:
      - dev
    networks:
      - presentation-network

  # PDF export service
  pdf-export:
    image: node:18-alpine
    container_name: telekom-pdf-export
    working_dir: /app
    volumes:
      - .:/app
      - ./pdf-exports:/app/pdf-exports
    command: >
      sh -c "
        apk add --no-cache chromium
        export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
        export PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
        if [ ! -d node_modules ]; then
          npm install
        fi
        npm run build
        npm run pdf
      "
    environment:
      - NODE_ENV=production
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
    profiles:
      - export
    networks:
      - presentation-network

networks:
  presentation-network:
    driver: bridge
    name: telekom-presentations

volumes:
  node_modules:
    name: telekom-presentations-modules